name: Build APIM with tests

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
    branches:
    - master
  schedule:
    - cron:  '0 20 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - id: 1
            segment: apim-integration-tests-api-common , apim-integration-tests-api-change-endpoint, apim-integration-tests-api-product, apim-integration-tests-api-lifecycle, apim-email-secondary-userstore-tests, apim-CORS-tests, apim-publisher-tests, apim-integration-tests-graphql
          - id: 2
            segment: apim-integration-tests-samples, apim-store-tests, admin-rest-api-tests, rest-api-tests, apim-mediation-tests, apim-integration-tests-without-restarts, apim-JWT-integration-tests, apim-urlsafe-JWT-integration-tests
          - id: 3
            segment: apim-integration-tests-application-sharing, apim-integration-tests-endpoint-security, apim-integration-tests-external-idp, apim-integration-emailusername-login, apim-integration-tests-workflow
      fail-fast: false
    steps:
    - name: Checkout master
      uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2
        restore-keys: ${{ runner.os }}-m2
    - name: Build carbon-apimgt without tests, skip AspectJ
      run: mvn clean install --file pom.xml -Dmaven.test.skip=true -Dskip.aspectj=true
    - name: Get carbon.apimgt.version
      run: mvn help:evaluate -Dexpression=project.version -q -DforceStdout > ../CARBON_APIMGT_VERSION_FILE
    - name: Print carbon.apimgt.version
      run: |
        echo $(cat ../CARBON_APIMGT_VERSION_FILE)
    - name: Checkout Product-APIM
      uses: actions/checkout@v1
      with: 
        repository: wso2/product-apim
        ref: refs/heads/master
    - name: Build product-apim with tests
      run: mvn clean install -Dcarbon.apimgt.version=$(cat ../CARBON_APIMGT_VERSION_FILE) -fae --file ../product-apim/pom.xml
      env:
        PRODUCT_APIM_TESTS: ${{ matrix.segment }}
    - name: Upload integration test coverage to Codecov
      uses: codecov/codecov-action@v1.2.1
      with:
        flags: integration_tests
        directory: ../product-apim/
