name: Build carbon-apimgt

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2
        restore-keys: ${{ runner.os }}-m2
    - name: Build carbon-apimgt with Tests, skipping AspectJ
      run: mvn clean install --file pom.xml -Dskip.aspectj=true
    - name: Upload unit test coverage to Codecov
      uses: codecov/codecov-action@v1.2.1
      with:
        flags: unit_tests
