name: Test Coverage Uploader

on:
  push:
    branches:
      - master

jobs:
  build-and-cover-carbon:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2
          restore-keys: ${{ runner.os }}-m2
      - name: Build carbon-apimgt - Include Tests - Skip AspectJ, NPM builds
        run: mvn clean install --file pom.xml -Dskip.aspectj=true -Dnpm.skip=true
      - name: Upload unit test coverage to Codecov
        uses: codecov/codecov-action@v1.2.1
        with:
          flags: unit_tests

  build-and-cover-product-apim:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - id: 1
          segment: apim-integration-tests-api-common,apim-integration-tests-api-change-endpoint,apim-integration-tests-api-product,apim-integration-tests-api-lifecycle,apim-email-secondary-userstore-tests
        - id: 2
          segment: apim-CORS-tests,apim-integration-tests-samples,apim-publisher-tests,apim-store-tests,apim-integration-tests-graphql,admin-rest-api-tests
        - id: 3
          segment: rest-api-tests,apim-mediation-tests,apim-integration-tests-without-restarts,apim-integration-tests-application-sharing,apim-JWT-integration-tests,apim-urlsafe-JWT-integration-tests
        - id: 4
          segment: apim-integration-tests-endpoint-security,apim-integration-tests-external-idp,apim-integration-emailusername-login,apim-integration-tests-workflow
#        - id: 5
#          segment: apim-integration-tests-api-product,apim-integration-tests-graphql
      fail-fast: false
    steps:
    - name: Checkout master
      uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2
        restore-keys: ${{ runner.os }}-m2
    - name: Build carbon-apimgt - Skip Tests, AspectJ, NPM builds
      run: mvn clean install --file pom.xml -Dmaven.test.skip=true -Dskip.aspectj=true -Dnpm.skip=true
    - name: Get carbon.apimgt.version
      run: mvn help:evaluate -Dexpression=project.version -q -DforceStdout > ../CARBON_APIMGT_VERSION_FILE
    - name: Print carbon.apimgt.version
      run: |
        echo $(cat ../CARBON_APIMGT_VERSION_FILE)
    - name: Checkout Product-APIM
      uses: actions/checkout@v1
      with:
        repository: malinthaprasan/product-apim
        ref: refs/heads/master
    - name: Build Product-Apim with Tests
      run: mvn clean install -Dcarbon.apimgt.version=$(cat ../CARBON_APIMGT_VERSION_FILE) -fae --file ../product-apim/pom.xml
      env:
        PRODUCT_APIM_TESTS: ${{ matrix.segment }}
    - name: Upload integration test coverage to Codecov
      uses: codecov/codecov-action@v1.2.1
      with:
        flags: integration_tests_${{ matrix.id }}
        directory: ../product-apim/

#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#    - name: Checkout master
#      uses: actions/checkout@v1
#    - name: Set up JDK 1.8
#      uses: actions/setup-java@v1
#      with:
#        java-version: 1.8
#    - uses: actions/setup-node@v1
#      with:
#        node-version: '14.x'
#    - name: Build carbon-apimgt with Tests, skipping AspectJ
#      run: mvn clean install --file pom.xml -Dskip.aspectj=true
#    - name: Get carbon.apimgt.version
#      run: mvn help:evaluate -Dexpression=project.version -q -DforceStdout > ../CARBON_APIMGT_VERSION_FILE
#    - name: Print carbon.apimgt.version
#      run: |
#        echo $(cat ../CARBON_APIMGT_VERSION_FILE)
#    - name: Checkout Product-APIM
#      uses: actions/checkout@v1
#      with:
#        repository: wso2/product-apim
#        ref: refs/heads/master
#    - name: Build Product-Apim with Tests
#      run: mvn clean install -Dcarbon.apimgt.version=$(cat ../CARBON_APIMGT_VERSION_FILE) -fae --file ../product-apim/pom.xml
#    - name: Upload unit test coverage to Codecov
#      uses: codecov/codecov-action@v1.2.1
#      with:
#        flags: unit_tests
#    - name: Upload integration test coverage to Codecov
#      uses: codecov/codecov-action@v1.2.1
#      with:
#        flags: integration_tests
#        directory: ../product-apim/
